# 2024-01-18 Experiment analysis

## Dependencies and setup

```{r}
library(tidyverse)
library(Hmisc)
```

```{r}
analysis_path <- "experiments/2024-01-18-better-abiotic-params/analysis"
data_path <- paste(analysis_path, "data", "world_summary.csv", sep = "/")
data <- read_csv(data_path)
```

## Data preprocessing

```{r}
data <- data %>%
  mutate(
    interaction_matrix = as.factor(interaction_matrix),
    graph_type = as.factor(graph_type),
    summary_mode = as.factor(summary_mode),
    update = as.numeric(update),
    SEED = as.factor(SEED)
  )

# data %>%
#   group_by(update, graph_type, interaction_matrix) %>%
#   summarise(
#     n = n(),
#   )

```

```{r}
plot_time_series <- function(summary_md, interaction_mat) {

  pd <- data %>% filter(
    summary_mode == summary_md & interaction_matrix == interaction_mat
  )

  plot <- pd %>%
    ggplot(
      aes(
        x = update,
        y = logged_mult_score,
        color = graph_type,
        fill = graph_type
      )
    ) +
    stat_summary(geom="line", fun="mean") +
    stat_summary(
      geom="ribbon",
      fun.data="mean_cl_boot",
      fun.args=list(conf.int=0.95),
      alpha=0.2,
      linetype=0
    )

  return(plot)
}
```

## Visualize transitionability scores over time

First, `logged_mult_score`:

```{r}
# grepl("diet", interaction_matrix)
plot <- plot_time_series(
  "ranked_threshold",
  "1464_diet−composition"
)
ggsave(
  paste(analysis_path, "1464_diet−composition_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)
```

```{r}

plot <- ggplot(
    filter(data, interaction_matrix == "1473_diet-composition" & summary_mode=="ranked_threshold"),
    aes(
      x = update,
      y = logged_mult_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  )
# plot <- plot_time_series(
#   "ranked_threshold",
#   "1473_diet−composition"
# )
ggsave(
  paste(analysis_path, "1473_diet−composition_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)
```



```{r}
plot <- ggplot(
    filter(
      data,
      interaction_matrix == "1512_diet-composition" & summary_mode == "ranked_threshold"
    ),
    aes(
      x = update,
      y = logged_mult_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  )
ggsave(
  paste(analysis_path, "1512_diet−composition_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)
```

```{r}
plot <- plot_time_series(
  "ranked_threshold",
  "class1"
)
ggsave(
  paste(analysis_path, "class1_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)

plot <- plot_time_series(
  "ranked_threshold",
  "class2"
)
ggsave(
  paste(analysis_path, "class2_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)

plot <- plot_time_series(
  "ranked_threshold",
  "class3"
)
ggsave(
  paste(analysis_path, "class3_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)


plot <- plot_time_series(
  "ranked_threshold",
  "class4"
)
ggsave(
  paste(analysis_path, "class4_ranked_thresh_diet_logged_mult_score.pdf", sep="/"),
  plot = plot
)

```

```{r}
ranked_thresh_class_p <- data %>%
  filter(
    summary_mode == "ranked_threshold" & grepl("class", interaction_matrix)
  ) %>%
  ggplot(
    aes(
      x = update,
      y = logged_mult_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  facet_wrap(~interaction_matrix, ncol=1)

ggsave(
  paste(analysis_path, "ranked_thresh_class_logged_mult_score.pdf", sep="/"),
  plot = ranked_thresh_class_p
)
```

```{r}
ranked_thresh_diet_additive_p <- data %>%
  filter(
    summary_mode == "ranked_threshold" & grepl("diet", interaction_matrix)
  ) %>%
  ggplot(
    aes(
      x = update,
      y = additive_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  facet_wrap(~interaction_matrix, ncol=1)

ggsave(
  paste(analysis_path, "ranked_thresh_diet_additive_score.pdf", sep="/"),
  plot = ranked_thresh_diet_additive_p
)

ranked_thresh_class_additive_p <- data %>%
  filter(
    summary_mode == "ranked_threshold" & grepl("class", interaction_matrix)
  ) %>%
  ggplot(
    aes(
      x = update,
      y = additive_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  facet_wrap(~interaction_matrix, ncol=1)

ggsave(
  paste(analysis_path, "ranked_thresh_class_additive_score.pdf", sep="/"),
  plot = ranked_thresh_class_additive_p
)
```

```{r}
ranked_diet_p <- data %>%
  filter(
    summary_mode == "ranked" & grepl("diet", interaction_matrix)
  ) %>%
  ggplot(
    aes(
      x = update,
      y = logged_mult_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  facet_wrap(~interaction_matrix, ncol=1)

ggsave(
  paste(analysis_path, "ranked_diet_logged_mult_score.pdf", sep="/"),
  plot = ranked_diet_p
)

ranked_class_p <- data %>%
  filter(
    summary_mode == "ranked" & grepl("class", interaction_matrix)
  ) %>%
  ggplot(
    aes(
      x = update,
      y = logged_mult_score,
      color = graph_type,
      fill = graph_type
    )
  ) +
  stat_summary(geom="line", fun="mean") +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  facet_wrap(~interaction_matrix, ncol=1)

ggsave(
  paste(analysis_path, "ranked_class_logged_mult_score.pdf", sep="/"),
  plot = ranked_class_p
)
```

```{r}
# adaptive_assembly_1000 <- data %>%
#   filter(
#     update == 750 & num_present_species > 0
#   ) %>%
#   ggplot(
#     aes(
#       x = graph_type,
#       y = smooth_adaptive_assembly_ratio,
#       color = graph_type
#     )
#   ) +
#   geom_boxplot() +
#   scale_y_continuous(
#     trans="pseudo_log",
#     breaks=c(0, 1, 10, 100, 1000, 10000)
#   ) +
#   facet_wrap(~interaction_matrix, ncol=1, scales = "free_y")
# adaptive_assembly_1000
# ggsave(
#   paste(analysis_path, "updateX.pdf", sep="/"),
#   plot = adaptive_assembly_1000
# )
```

